pipeline {
    agent any
    
    environment {
        SERVICE_NAME = 'condature'
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials'
        DOCKER_IMAGE = "dalirom123/condature:${env.BUILD_NUMBER}"
        SONAR_CREDENTIALS_ID = 'sonar-credentials'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('condature') {
                    sh 'mvn clean install'
                }
            }
        }
        
        stage('Unit Tests + JaCoCo') {
            steps {
                dir('condature') {
                    sh 'mvn org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report'
                }
            }
            post {
                always {
                    dir('condature') {
                        junit testResults: 'target/surefire-reports/*.xml', allowEmptyResults: true
                    }
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('condature') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=${SERVICE_NAME} -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml'
                    }
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('condature') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
        stage('SonarQube Analysis') {
            steps {
                dir('condature') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=${SERVICE_NAME} -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml'
                    }
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('condature') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
    post {
        success {
            build job: 'Global-CD', wait: false
        }
    }
}
