pipeline {
    agent any
    
    environment {
        SERVICE_NAME = 'eureka-server'
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials'
        DOCKER_IMAGE = "yourdockerhubusername/$SERVICE_NAME:${env.BUILD_NUMBER}"
        SONAR_CREDENTIALS_ID = 'sonar-credentials'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build & Test') {
            steps {
                dir('eureka-server') {
                    sh 'mvn clean install'
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('eureka-server') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=${SERVICE_NAME}'
                    }
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('eureka-server') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
}
