sonar.projectKey=freelink-frontend
sonar.projectName=Freelink Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage/freelink-evaluation-recompense-front/lcov.info
