apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: int
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: qualif
---
apiVersion: v1
kind: Namespace
metadata:
  name: preprod
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
