apiVersion: v1
kind: Service
metadata:
  name: porjectservice
  namespace: dev
spec:
  selector:
    app: porjectservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
  type: ClusterIP
