apiVersion: v1
kind: Service
metadata:
  name: gestion-planing
  namespace: dev
spec:
  selector:
    app: gestion-planing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8092
  type: ClusterIP
