apiVersion: apps/v1
kind: Deployment
metadata:
  name: condature
  namespace: freelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: condature
  template:
    metadata:
      labels:
        app: condature
    spec:
      containers:
      - name: condature
        image: dalirom123/condature:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/condidature_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: condature
  namespace: freelink
spec:
  type: ClusterIP
  selector:
    app: condature
  ports:
    - port: 8082
      targetPort: 8082
