apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: freelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
      - name: evaluation-service
        image: dalirom123/evaluation-service:latest
        ports:
        - containerPort: 8086
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/projet_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: freelink
spec:
  type: ClusterIP
  selector:
    app: evaluation-service
  ports:
    - port: 8086
      targetPort: 8086
