apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-planing
  namespace: freelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-planing
  template:
    metadata:
      labels:
        app: gestion-planing
    spec:
      containers:
      - name: gestion-planing
        image: dalirom123/gestion-planing:latest
        ports:
        - containerPort: 8092
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/gestion_planing?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-planing
  namespace: freelink
spec:
  type: ClusterIP
  selector:
    app: gestion-planing
  ports:
    - port: 8092
      targetPort: 8092
