apiVersion: apps/v1
kind: Deployment
metadata:
  name: reclamation
  namespace: freelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reclamation
  template:
    metadata:
      labels:
        app: reclamation
    spec:
      containers:
      - name: reclamation
        image: dalirom123/reclamation:latest
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: "-Xms64m -Xmx256m"
        resources:
          limits:
            memory: "400Mi"
          requests:
            memory: "250Mi"
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: reclamation-service
  namespace: freelink
spec:
  type: ClusterIP
  selector:
    app: reclamation
  ports:
    - port: 8085
      targetPort: 8085

