apiVersion: apps/v1
kind: Deployment
metadata:
  name: reclamation
  namespace: freelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reclamation
  template:
    metadata:
      labels:
        app: reclamation
    spec:
      containers:
      - name: reclamation
        image: dalirom123/reclamation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/reclamationdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: reclamation
  namespace: freelink
spec:
  type: ClusterIP
  selector:
    app: reclamation
  ports:
    - port: 8085
      targetPort: 8085
