apiVersion: apps/v1
kind: Deployment
metadata:
  name: skills-service
  namespace: freelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skills-service
  template:
    metadata:
      labels:
        app: skills-service
    spec:
      containers:
      - name: skills-service
        image: dalirom123/skills-service:latest
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: skills-service
  namespace: freelink
spec:
  type: ClusterIP
  selector:
    app: skills-service
  ports:
    - port: 8084
      targetPort: 8084
