apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-tracking-service
  namespace: freelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-tracking-service
  template:
    metadata:
      labels:
        app: time-tracking-service
    spec:
      containers:
      - name: time-tracking-service
        image: dalirom123/time-tracking-service:latest
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: "-Xms64m -Xmx128m"
        resources:
          limits:
            memory: "300Mi"
          requests:
            memory: "150Mi"
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: time-tracking-service-service
  namespace: freelink
spec:
  type: ClusterIP
  selector:
    app: time-tracking-service
  ports:
    - port: 8089
      targetPort: 8089
