apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-tracking-service
  namespace: freelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-tracking-service
  template:
    metadata:
      labels:
        app: time-tracking-service
    spec:
      containers:
                env:
            - name: JAVA_OPTS
              value: "-Xms64m -Xmx128m"
      - name: time-tracking-service
        image: dalirom123/time-tracking-service:latest
        imagePullPolicy: Always
        resources:
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
        ports:
        - containerPort: 8088
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/time_tracking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: time-tracking-service
  namespace: freelink
spec:
  type: ClusterIP
  selector:
    app: time-tracking-service
  resources:
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
        ports:
    - port: 8088
      targetPort: 8088

