apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
      - name: reservation-service
        image: reservation-service:latest
        ports:
        - containerPort: 8088
