pipeline {
    agent any
    
    environment {
        SERVICE_NAME = 'front'
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials'
        DOCKER_IMAGE = "yourdockerhubusername/$SERVICE_NAME:${env.BUILD_NUMBER}"
        SONAR_CREDENTIALS_ID = 'sonar-credentials'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir('sofia-pidev-front-Gestion-skills') {
                    sh 'npm install'
                }
            }
        }
        
        stage('Test (Jasmine)') {
            steps {
                dir('sofia-pidev-front-Gestion-skills') {
                    sh 'npm run test -- --watch=false --browsers=ChromeHeadless'
                }
            }
        }
        
        stage('Build') {
            steps {
                dir('sofia-pidev-front-Gestion-skills') {
                    sh 'npm run build'
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('sofia-pidev-front-Gestion-skills') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'npx sonar-scanner -Dsonar.projectKey=${SERVICE_NAME} -Dsonar.sources=src'
                    }
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('sofia-pidev-front-Gestion-skills') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
}
