apiVersion: v1
kind: Service
metadata:
  name: gestion-planning-front
  namespace: dev
spec:
  selector:
    app: gestion-planning-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
