pipeline {
    agent any
    
    environment {
        SERVICE_NAME = 'porjectservice'
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials'
        DOCKER_IMAGE = "dalirom123/porjectservice:${env.BUILD_NUMBER}"
        SONAR_CREDENTIALS_ID = 'sonar-credentials'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('porjectservice') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
        
        stage('Unit Tests (Jacoco)') {
            steps {
                dir('porjectservice') {
                    sh 'mvn org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report || true'
                }
            }
            post {
                always {
                    dir('porjectservice') {
                        junit 'target/surefire-reports/*.xml'
                        jacoco(
                            execPattern: 'target/*.exec',
                            classPattern: 'target/classes',
                            sourcePattern: 'src/main/java'
                        )
                    }
                }
            }
        }
        
        
        
        stage('SonarQube Analysis') {
            steps {
                dir('porjectservice') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=${SERVICE_NAME} -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml'
                    }
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('porjectservice') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
}
