stages:
  - build
  - test
  - sonarqube

image: maven:3.8.6-eclipse-temurin-17

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test

sonarqube:
  stage: sonarqube
  script:
    - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar -Dsonar.host.url=https://dreaded-sudoku-unopened.ngrok-free.dev -Dsonar.login=$SONAR_TOKEN
  only:
    - master
