apiVersion: v1
kind: Service
metadata:
  name: reclamation
  namespace: dev
spec:
  selector:
    app: reclamation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP
