spring.application.name=gestion-planing

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gestion_planing?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${SERVER_PORT:8086}

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

sentry.dsn=${SENTRY_DSN:}
sentry.environment=${SENTRY_ENVIRONMENT:dev}
sentry.release=${SENTRY_RELEASE:${spring.application.name}@0.0.1-SNAPSHOT}
sentry.traces-sample-rate=${SENTRY_TRACES_SAMPLE_RATE:0.0}
