spring.application.name=gestion-planing

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_planing?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8086

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false