pipeline {
    agent any
    
    environment {
        SERVICE_NAME = 'gestion-planning-front'
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials'
        DOCKER_IMAGE = "dalirom123/gestion-planning-front:${env.BUILD_NUMBER}"
        SONAR_CREDENTIALS_ID = 'sonar-credentials'
        NODE_OPTIONS = '--max-old-space-size=4096'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir('gestion-planning-front') {
                    sh '''
                        rm -rf node_modules package-lock.json
                        npm cache clean --force
                        
                        npm config set fetch-retries 5
                        npm config set fetch-retry-factor 2
                        npm config set fetch-retry-mintimeout 20000
                        npm config set fetch-retry-maxtimeout 120000
                        
                        npm config set registry https://registry.npmjs.org/
                        
                        npm install --legacy-peer-deps --no-audit --no-fund
                    '''
                }
            }
        }
        
        stage('Test (Jasmine)') {
            steps {
                dir('gestion-planning-front') {
                    sh '''
                        export CHROME_BIN=/usr/bin/chromium-browser
                        if [ ! -f "$CHROME_BIN" ]; then
                          export CHROME_BIN=/usr/bin/chromium
                        fi
                        npm run test -- --watch=false --browsers=ChromeHeadless || true
                    '''
                }
            }
        }
        
        stage('Build') {
            steps {
                dir('gestion-planning-front') {
                    sh 'npm run build'
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('gestion-planning-front') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'npx sonar-scanner -Dsonar.projectKey=${SERVICE_NAME} -Dsonar.sources=src'
                    }
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('gestion-planning-front') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
    post {
        success {
            build job: 'Global-CD', wait: false
        }
    }
}
